# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ricardo's Blog
email: __rs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will contain some useful code and tips (I hope)...	  
baseurl: "" 
url: "http://ssricardo.github.io" # the base hostname & protocol for your site
twitter_username: noooo
github_username:  ssricardo

# Build settings
markdown: kramdown
