# Site settings
title: Ricardo's Notes
#email: __rs@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site will contain some useful code and tips (I hope) for developers.  
  Specially focused on Java.
baseurl: "" 
url: "http://ssricardo.github.io"
#twitter_username: noooo
github_username:  ssricardo

# Build settings
markdown: kramdown

theme: jekyll-theme-tactile