source 'https://rubygems.org'
gem 'jekyll', '~> 4.4'
gem 'webrick', '~> 1.8'
gem 'jekyll-theme-yat'
gem 'jekyll-spaceship'
gem 'ostruct'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
